dataset:
    # mandatory dataset options
    name: "coco_subset"
    num_classes: 91  # your highest class index + 1
    train_val_split: 0.8

    # options depending on your dataset
    set: "val"  # or train
    coco_path: "data/coco/"
    target_classes: ["dog", "cat", "person"]

model:
    dim_model: 256
    n_heads: 8
    n_queries: 100

losses:
    # lambdas are the loss weights
    lambda_matcher_classes: 1
    lambda_matcher_giou: 2
    lambda_matcher_l1: 5

    lambda_loss_classes: 1
    lambda_loss_giou: 2
    lambda_loss_l1: 5

    no_class_weight: 0.001

training:
    epochs: 50
    batch_size: 2
    effective_batch_size: 32
    lr: 0.001

